### ISSUE TITLE
[Suggestion] Command-history between restarts

### ISSUE THREAD

**Issue by Boy0000** [darmiel/fuzzy-mc#2]
Much like vanilla now saves the last 50-ish commands, would be nice if Fuzzy `(.minecraft/command_history.txt)`
1. Included those commands by default instead of empty
2. Configurable command-history cache

![image](https://github.com/darmiel/fuzzy-mc/assets/62521371/a9b0a460-ff97-4e9e-87dd-94bd6c548e27)

**Comment by darmiel** [comment]
Thank you for the idea! I had also considered using this file during the implementation. However, I wasn't sure what exactly the file was about (or whether it only exists in debug mode) because I hadn't found anything about it online (seems to be relatively new?).  I will add it in the next version, thanks for the suggestion!

**Comment by Boy0000** [comment]
https://minecraft.wiki/w/Java_Edition_1.20.2#Command%20format

Came with 1.20.2 yeah

![image](https://github.com/darmiel/fuzzy-mc/assets/62521371/c0336eb3-b6c3-46b9-a32c-3a5356061b57)

**Comment by darmiel** [comment]
I have added the command history from `command_history.txt`. If you want you can try & test the version here: [fuzzy-1.6.0.zip](https://github.com/darmiel/fuzzy-mc/files/13591468/fuzzy-1.6.0.zip) (It's disabled by default, however. You need to enable it in the config)

History-loaded commands are indicated with a `*`:
![image](https://github.com/darmiel/fuzzy-mc/assets/71837281/294086ef-0970-4cc3-b2ca-10b3a9ec355a)



But what do you mean by a configurable command cache (2.)? Should the mod create its own `command_history` somewhere (with possibly more than 50 commands)?
