### ISSUE TITLE
[Suggestion] Select commands by clicking them

### ISSUE THREAD

**Issue by VelizarBG** [darmiel/fuzzy-mc#6]
I'd appreciate it if it would be possible to select commands by clicking them, as an alternative to using the arrow keys.
It would also be nice if they can be executed via a double-click - left can be executing and right can be suggesting.
Thank you in advance.

**Comment by darmiel** [comment]
I agree this would be a nice suggestion. But because of my "slight" mis-use of the `TextFieldWidget` component in https://github.com/darmiel/fuzzy-mc/blob/main/src/client/java/io/d2a/fuzzy/screens/widget/SearchTextFieldWidget.java I had to disable any mouse events to fix focusing issues. I'll see if I can find another way to make mouse events work again, but as I'm short on time at the moment, that's probably not going to happen any time soon

**Comment by VelizarBG** [comment]
That's fine. In the meantime, I've opened a PR that comes close enough to cover this issue for now.

**Comment by darmiel** [comment]
> That's fine. In the meantime, I've opened a PR that comes close enough to cover this issue for now.

awesome, thank you! Will try it out today

**Comment by VelizarBG** [comment]
Neat! On a bit of an unrelated note - it's silly of me to ask, but I'm sure you won't mind if I implement the fuzzy setting inside [my own mod](https://github.com/VelizarBG/suggestion-tweaker), right?

**Comment by darmiel** [comment]
of course not, go ahead! :)

**Comment by VelizarBG** [comment]
Very nice, thank you!
